window.FIRST100_LOCALES = {
  de: {
    nav: ["Start", "Journey", "Personen", "Notizen"], all: "Alle Experiences ↗",
    dashboard: { context: "FIKTIVES BEISPIEL · DEMOCO · CUSTOMER SUCCESS", title: "Willkommen bei DemoCo.", intro: "DemoCo ist ein fiktives B2B-Softwareunternehmen. Die Plattform hilft Unternehmen, Kundenprojekte und interne Abläufe zu organisieren. Du startest im Customer Success.", goal: "Dein Ziel", goalText: "Nach 100 Tagen ein kleines Kundenportfolio selbst betreuen", program: "Dein Ablauf", programText: "100 Tage, aufgeteilt in 5 Phasen mit je 3 Missionen", adaptable: "Vollständig anpassbar", adaptableText: "Diese Demo zeigt eine mögliche Journey für Customer Success. Rolle, Inhalte, Zeitraum, Sprache, Gestaltung und Integrationen werden an das jeweilige Unternehmen angepasst.", next: "Als Nächstes", progress: "Dein Fortschritt", allMissions: "Alle Missionen", meetings: "Kalenderentwürfe", plan: "Entwurf erstellen", how: "So funktioniert es", steps: ["Mission öffnen", "Aufgabe im Arbeitsalltag machen", "Ergebnisse eintragen", "Mission abschließen"], local: "Deine Einträge und Kalenderentwürfe werden nur in diesem Browser gespeichert.", noMeetings: "Noch keine Kalenderentwürfe.", showPeople: "Personen anzeigen", open: "Mission öffnen" },
    journey: { meta: "100 TAGE · 5 PHASEN · JE 3 MISSIONEN", title: "Deine Journey", intro: "Die 100 Tage sind in fünf Zeitabschnitte gegliedert. In jeder Phase gibt es drei Missionen. Du siehst immer nur die drei, die gerade zu dieser Phase gehören.", open: "Öffnen →", back: "← Zur Journey" },
    mission: { number: "Mission", of: "von 15", steps: "So gehst du vor", results: "Deine Ergebnisse", savedLocal: "Diese Einträge gehören zu dieser Mission und werden automatisch gespeichert.", save: "Zwischenspeichern", finish: "Speichern und abschließen", update: "Änderungen speichern", done: "Erledigt ✓", saved: "Gespeichert.", autosaved: "Automatisch gespeichert.", required: "Bitte füll zuerst alle Pflichtfelder aus.", optional: "optional", support: "Dafür brauchst du", scheduleWith: "Gespräch vormerken", completeTitle: "Mission abgeschlossen.", completeText: "Deine Ergebnisse sind gespeichert. Du kannst direkt mit der nächsten Mission weitermachen.", next: "Weiter zur nächsten Mission", finalTitle: "Alle 15 Missionen abgeschlossen.", finalText: "Deine First 100 Days Journey ist vollständig. Du kannst deine Einträge weiterhin öffnen.", overview: "Zur vollständigen Journey" },
    people: { meta: "DEIN NETZWERK", title: "Personen kennenlernen", intro: "Für einige Missionen brauchst du die Perspektive anderer Teams. Hier kannst du einen Kalenderentwurf vorbereiten und herunterladen.", schedule: "Kalenderentwurf erstellen" },
    notes: { meta: "PRIVAT · NUR AUF DIESEM GERÄT", title: "Meine Notizen", intro: "Für zusätzliche Fragen und Beobachtungen. Die Eingabefelder der einzelnen Missionen findest du direkt in der jeweiligen Mission.", label: "Neue Notiz", placeholder: "Was möchtest du festhalten?", save: "Notiz speichern", empty: "Noch keine Notizen.", remove: "Löschen", deleted: "Notiz gelöscht.", undo: "Rückgängig" },
    a11y: { skip: "Zum Inhalt", home: "Zur Startseite", nav: "Hauptnavigation", language: "Sprache wählen", progress: "Gesamtfortschritt", mission: "Aktuelle Mission", phases: "Journey-Phasen", noteCategory: "Notiz einordnen", close: "Dialog schließen", download: "Kalendereintrag herunterladen" },
    demo: { reset: "Demo zurücksetzen", confirm: "Alle Antworten, Fortschritte, Notizen und Kalenderentwürfe in diesem Browser löschen?", done: "Die Demo wurde zurückgesetzt." },
    phases: [["Tag 1–10","Orientieren"],["Tag 11–30","Zusammenhänge verstehen"],["Tag 31–60","Selbst ausprobieren"],["Tag 61–90","Verantwortung übernehmen"],["Tag 91–100","Wissen weitergeben"]]
  },
  en: {
    nav: ["Home", "Journey", "People", "Notes"], all: "All experiences ↗",
    dashboard: { context: "FICTIONAL EXAMPLE · DEMOCO · CUSTOMER SUCCESS", title: "Welcome to DemoCo.", intro: "DemoCo is a fictional B2B software company. Its platform helps companies organise client projects and internal workflows. You are joining the Customer Success team.", goal: "Your goal", goalText: "Manage a small client portfolio independently after 100 days", program: "Your journey", programText: "100 days, divided into 5 phases with 3 missions each", adaptable: "Fully adaptable", adaptableText: "This demo shows one possible Customer Success journey. The role, content, timeframe, language, visual identity and integrations are adapted to each organisation.", next: "Up next", progress: "Your progress", allMissions: "All missions", meetings: "Calendar drafts", plan: "Create draft", how: "How it works", steps: ["Open a mission", "Complete the task during your workday", "Record your findings", "Complete the mission"], local: "Your entries and calendar drafts are stored only in this browser.", noMeetings: "No calendar drafts yet.", showPeople: "View people", open: "Open mission" },
    journey: { meta: "100 DAYS · 5 PHASES · 3 MISSIONS EACH", title: "Your journey", intro: "The 100 days are divided into five time periods. Each phase contains three missions. You only see the three missions that belong to the current phase.", open: "Open →", back: "← Back to journey" },
    mission: { number: "Mission", of: "of 15", steps: "What to do", results: "Your findings", savedLocal: "These entries belong to this mission and are saved automatically.", save: "Save draft", finish: "Save and complete", update: "Save changes", done: "Completed ✓", saved: "Saved.", autosaved: "Saved automatically.", required: "Please complete all required fields first.", optional: "optional", support: "Who you need", scheduleWith: "Prepare meeting", completeTitle: "Mission completed.", completeText: "Your findings are saved. You can continue directly with the next mission.", next: "Continue to the next mission", finalTitle: "All 15 missions completed.", finalText: "Your First 100 Days journey is complete. You can still open all your entries.", overview: "View the full journey" },
    people: { meta: "YOUR NETWORK", title: "Meet the team", intro: "Some missions require input from other teams. You can prepare and download a calendar event here.", schedule: "Prepare calendar event" },
    notes: { meta: "PRIVATE · THIS DEVICE ONLY", title: "My notes", intro: "For any additional questions and observations. Mission-specific fields are available inside each mission.", label: "New note", placeholder: "What would you like to remember?", save: "Save note", empty: "No notes yet.", remove: "Delete", deleted: "Note deleted.", undo: "Undo" },
    a11y: { skip: "Skip to content", home: "Go to home", nav: "Main navigation", language: "Choose language", progress: "Overall progress", mission: "Current mission", phases: "Journey phases", noteCategory: "Choose note category", close: "Close dialog", download: "Download calendar event" },
    demo: { reset: "Reset demo", confirm: "Delete all answers, progress, notes and calendar drafts stored in this browser?", done: "The demo has been reset." },
    phases: [["Days 1–10","Get oriented"],["Days 11–30","Understand the context"],["Days 31–60","Try it yourself"],["Days 61–90","Take responsibility"],["Days 91–100","Share what you know"]]
  },
  fr: {
    nav: ["Accueil", "Parcours", "Équipe", "Notes"], all: "Toutes les expériences ↗",
    dashboard: { context: "EXEMPLE FICTIF · DEMOCO · CUSTOMER SUCCESS", title: "Bienvenue chez DemoCo.", intro: "DemoCo est une entreprise fictive de logiciels B2B. Sa plateforme aide les entreprises à organiser leurs projets clients et leurs processus internes. Vous rejoignez l’équipe Customer Success.", goal: "Votre objectif", goalText: "Gérer un petit portefeuille clients en autonomie après 100 jours", program: "Votre parcours", programText: "100 jours, répartis en 5 phases de 3 missions", adaptable: "Entièrement adaptable", adaptableText: "Cette démo présente un parcours possible pour le Customer Success. Le rôle, les contenus, la durée, la langue, l’identité visuelle et les intégrations sont adaptés à chaque entreprise.", next: "Prochaine étape", progress: "Votre progression", allMissions: "Toutes les missions", meetings: "Brouillons de calendrier", plan: "Créer un brouillon", how: "Comment ça marche", steps: ["Ouvrir une mission", "Faire la tâche dans le cadre de votre travail", "Noter vos résultats", "Terminer la mission"], local: "Vos réponses et vos brouillons de calendrier restent enregistrés dans ce navigateur.", noMeetings: "Aucun brouillon pour le moment.", showPeople: "Voir l’équipe", open: "Ouvrir la mission" },
    journey: { meta: "100 JOURS · 5 PHASES · 3 MISSIONS PAR PHASE", title: "Votre parcours", intro: "Les 100 jours sont répartis en cinq périodes. Chaque phase contient trois missions. Vous ne voyez que les trois missions qui correspondent à la phase en cours.", open: "Ouvrir →", back: "← Retour au parcours" },
    mission: { number: "Mission", of: "sur 15", steps: "Comment procéder", results: "Vos résultats", savedLocal: "Ces réponses sont liées à cette mission et sont enregistrées automatiquement.", save: "Enregistrer", finish: "Enregistrer et terminer", update: "Enregistrer les modifications", done: "Terminée ✓", saved: "Enregistré.", autosaved: "Enregistré automatiquement.", required: "Merci de remplir tous les champs obligatoires.", optional: "facultatif", support: "Personnes à contacter", scheduleWith: "Préparer un rendez-vous", completeTitle: "Mission terminée.", completeText: "Vos résultats sont enregistrés. Vous pouvez passer directement à la mission suivante.", next: "Passer à la mission suivante", finalTitle: "Les 15 missions sont terminées.", finalText: "Votre parcours First 100 Days est terminé. Vous pouvez toujours consulter vos réponses.", overview: "Voir le parcours complet" },
    people: { meta: "VOTRE RÉSEAU", title: "Rencontrer l’équipe", intro: "Certaines missions nécessitent le point de vue d’autres équipes. Vous pouvez préparer et télécharger un événement de calendrier ici.", schedule: "Préparer l’événement" },
    notes: { meta: "PRIVÉ · UNIQUEMENT SUR CET APPAREIL", title: "Mes notes", intro: "Pour vos questions et observations supplémentaires. Les champs propres à chaque mission se trouvent directement dans la mission.", label: "Nouvelle note", placeholder: "Que souhaitez-vous noter ?", save: "Enregistrer la note", empty: "Aucune note pour le moment.", remove: "Supprimer", deleted: "Note supprimée.", undo: "Annuler" },
    a11y: { skip: "Aller au contenu", home: "Retour à l’accueil", nav: "Navigation principale", language: "Choisir la langue", progress: "Progression globale", mission: "Mission en cours", phases: "Phases du parcours", noteCategory: "Choisir une catégorie", close: "Fermer la fenêtre", download: "Télécharger l’événement" },
    demo: { reset: "Réinitialiser la démo", confirm: "Supprimer toutes les réponses, la progression, les notes et les projets de calendrier enregistrés dans ce navigateur ?", done: "La démo a été réinitialisée." },
    phases: [["Jours 1–10","S’orienter"],["Jours 11–30","Comprendre le contexte"],["Jours 31–60","Essayer soi-même"],["Jours 61–90","Prendre des responsabilités"],["Jours 91–100","Transmettre ses connaissances"]]
  }
};

window.FIRST100_MISSIONS = {
  en: {
    "customer-view":["Test the product as a new client","Set up a test account without internal instructions. Notice what is clear and where you get stuck.",["Start with the public guide.","Record one good moment and one difficult moment.","Write down a question for a client."],[["What was clear straight away?","The first step was clear because …"],["Where did you get stuck?","Describe the exact point."],["What would you ask a client?","What did you expect at this point?"]]],
    "three-views":["Get three perspectives","Speak with one person each from Sales, Support and Product. Ask everyone what clients need at the start and where misunderstandings occur.",["Schedule three short conversations.","Ask the same questions each time.","Compare the answers."],[["What did Sales say?","Key points."],["What did Support say?","Key points."],["What did Product say?","Key points."],["What did you notice?","Similarities and differences."]]],
    "unwritten-rule":["Find an unwritten rule","Observe a real work situation and note what is not covered by the handbook.",["Choose a meeting or handover.","Observe how decisions are actually made.","Check your assumption with your buddy."],[["What did you observe?","Meeting, handover or another situation."],["What unwritten rule did you notice?","For example, decisions are confirmed afterwards."],["What would you like to ask?","A factual question for your buddy."]]],
    "listen-call":["Observe a client call","Listen to a client call and focus on goals, uncertainty and next steps.",["Read the key client information.","Take brief notes during the call.","Compare them with the host afterwards."],[["What was the client trying to achieve?","The main goal."],["Where did you hear uncertainty?","A specific moment."],["What was agreed?","Task, owner and date."]]],
    "case-rebuild":["Reconstruct a difficult case","Review a closed case backwards: what happened and when could the team have acted?",["Choose an anonymised case.","Put the events in order.","Mark the earliest useful intervention."],[["What happened?","Short sequence."],["Which signal appeared early?","Usage, communication or another sign."],["What could the team have done?","One concrete action."]]],
    "risk-signal":["Assess a risk signal","A client barely uses the product but says everything is fine. Decide what to check next.",["Collect the available facts.","Separate facts from assumptions.","Choose the next step."],[["What facts do you have?","Only confirmed information."],["What are you assuming?","A possible explanation."],["What will you do next?","Action and people involved."]]],
    "first-part":["Lead part of a client call","Prepare and lead one clearly defined part of a real client call.",["Agree on your part beforehand.","Prepare the goal and two questions.","Ask for feedback immediately afterwards."],[["Which part will you lead?","Opening, review or next steps."],["What is your goal?","What should be clear afterwards?"],["Which two questions will you ask?","Write both questions."]]],
    "use-feedback":["Use feedback straight away","Choose one piece of feedback from your last call and plan how to use it next time.",["Write the feedback down precisely.","Turn it into observable behaviour.","Choose a suitable situation."],[["What feedback did you receive?","As close to the original wording as possible."],["What will you do differently?","One concrete behaviour."],["When will you try it?","Call or date."]]],
    "success-plan":["Create your first success plan","Create a simple plan for an existing client with your lead.",["Clarify the client’s business goal.","Define a visible sign of success.","Agree on the next step."],[["What is the client’s goal?","Use the client’s own language."],["How will you recognise success?","A visible or measurable sign."],["What is the next step?","Task, owner and date."]]],
    "small-portfolio":["Take on your first clients","Take on a small portfolio. Record only what you need for the next good decision.",["Agree on the scope with your lead.","Review goals, status and open points.","Plan the next contact."],[["Which clients are you taking on?","Names or internal codes."],["Where is action needed?","One sentence per client."],["What do you need to clarify?","An open decision or concern."]]],
    "recovery-plan":["Draft a recovery plan","Choose an at-risk client and plan the next realistic step.",["Summarise the risk signals.","Identify who needs to be involved.","Propose a testable action."],[["Why is the client at risk?","Observed signals."],["Who should be involved?","On both sides."],["What do you propose?","Action, goal and review date."]]],
    "tradeoff":["Explain a difficult decision","Work through a case where the client request, effort and responsible use do not align.",["Name the interests involved.","Consider possible consequences.","Decide and explain why."],[["Which interests conflict?","Client, users and company."],["What could happen?","Short and long term."],["What is your decision?","Decision and reasoning."]]],
    "success-story":["Document a client success","Describe what improved for the client and what you contributed.",["Describe the starting point.","Show the most important change.","Note what you would repeat."],[["What was the starting point?","Problem or goal."],["What changed?","Concrete benefit."],["What did you learn?","One point for next time."]]],
    "explain":["Explain it to a new colleague","Explain an area you now know well to someone newer.",["Choose a manageable topic.","Avoid internal abbreviations.","Ask what is still unclear."],[["What are you explaining?","One defined topic."],["What was difficult to understand?","Question or uncertainty."],["What would you change?","One improvement."]]],
    "fresh-eyes":["Review your first 100 days","Look back on your first 100 days. You decide what stays private and what you share.",["Review your entries.","Choose one thing to keep and one to improve.","Decide what you want to share."],[["What made the start easier?","What should stay?"],["What was unnecessarily difficult?","Process, information or situation."],["What should change?","One realistic suggestion."],["What would you like to share?","You may leave this blank.",false]]]
  },
  fr: {
    "customer-view":["Testez le produit comme un nouveau client","Créez un compte test sans consignes internes. Repérez ce qui est clair et les points de blocage.",["Commencez par le guide public.","Notez un point positif et une difficulté.","Formulez une question à poser à un client."],[["Qu’est-ce qui était clair dès le départ ?","La première étape était claire parce que…"],["Où avez-vous bloqué ?","Décrivez l’étape précise."],["Que demanderiez-vous à un client ?","Qu’attendiez-vous à ce moment-là ?"]]],
    "three-views":["Recueillez trois points de vue","Échangez avec une personne des équipes Sales, Support et Produit. Posez les mêmes questions à chacune.",["Planifiez trois échanges courts.","Posez les mêmes questions.","Comparez les réponses."],[["Que dit l’équipe Sales ?","Les points essentiels."],["Que dit le Support ?","Les points essentiels."],["Que dit l’équipe Produit ?","Les points essentiels."],["Qu’avez-vous remarqué ?","Points communs et différences."]]],
    "unwritten-rule":["Repérez une règle implicite","Observez une situation réelle et notez ce qui n’apparaît dans aucun manuel.",["Choisissez une réunion ou une passation.","Observez comment les décisions sont prises.","Vérifiez votre hypothèse avec votre buddy."],[["Quelle situation avez-vous observée ?","Réunion, passation ou autre."],["Quelle règle implicite avez-vous repérée ?","Par exemple, les décisions sont confirmées après la réunion."],["Que souhaitez-vous demander ?","Une question factuelle à votre buddy."]]],
    "listen-call":["Observez un échange client","Écoutez un échange client en vous concentrant sur les objectifs, les incertitudes et la suite.",["Lisez les informations principales.","Prenez quelques notes.","Comparez-les ensuite avec la personne qui menait l’échange."],[["Quel était l’objectif du client ?","L’objectif principal."],["Où avez-vous perçu une hésitation ?","Un moment précis."],["Qu’est-ce qui a été convenu ?","Tâche, responsable et date."]]],
    "case-rebuild":["Reconstituez un cas difficile","Reprenez un cas clôturé à rebours : que s’est-il passé et quand aurait-on pu agir ?",["Choisissez un cas anonymisé.","Remettez les événements dans l’ordre.","Repérez la première intervention utile."],[["Que s’est-il passé ?","Résumé chronologique."],["Quel signal était visible tôt ?","Usage, communication ou autre."],["Qu’aurait-on pu faire ?","Une action concrète."]]],
    "risk-signal":["Évaluez un signal de risque","Un client utilise peu le produit mais dit que tout va bien. Décidez quoi vérifier ensuite.",["Rassemblez les faits.","Séparez faits et hypothèses.","Choisissez l’étape suivante."],[["Quels faits connaissez-vous ?","Uniquement les informations confirmées."],["Quelle est votre hypothèse ?","Une explication possible."],["Que faites-vous ensuite ?","Action et personnes concernées."]]],
    "first-part":["Prenez en charge une partie de l’échange","Préparez et menez une partie clairement définie d’un échange client réel.",["Validez votre partie en amont.","Préparez l’objectif et deux questions.","Demandez un retour juste après."],[["Quelle partie prenez-vous en charge ?","Introduction, bilan ou prochaines étapes."],["Quel est votre objectif ?","Qu’est-ce qui doit être clair ensuite ?"],["Quelles questions poserez-vous ?","Écrivez les deux questions."]]],
    "use-feedback":["Mettez un retour en pratique","Choisissez un retour reçu après votre dernier échange et préparez sa mise en pratique.",["Notez précisément le retour.","Traduisez-le en comportement observable.","Choisissez une situation adaptée."],[["Quel retour avez-vous reçu ?","Au plus proche des mots employés."],["Que ferez-vous différemment ?","Un comportement concret."],["Quand allez-vous essayer ?","Échange ou date."]]],
    "success-plan":["Créez votre premier Success Plan","Élaborez avec votre responsable un plan simple pour un client existant.",["Clarifiez l’objectif métier.","Définissez un signe de réussite.","Convenez de la prochaine étape."],[["Quel est l’objectif du client ?","Avec ses propres mots."],["Comment reconnaître la réussite ?","Un signe visible ou mesurable."],["Quelle est la prochaine étape ?","Tâche, responsable et date."]]],
    "small-portfolio":["Prenez en charge vos premiers clients","Reprenez un petit portefeuille. Notez seulement ce qui aide à prendre la prochaine bonne décision.",["Définissez le périmètre avec votre responsable.","Vérifiez objectifs, statut et points ouverts.","Planifiez le prochain contact."],[["Quels clients reprenez-vous ?","Noms ou codes internes."],["Où faut-il agir ?","Une phrase par client."],["Que devez-vous clarifier ?","Une décision ou une incertitude."]]],
    "recovery-plan":["Préparez un plan de redressement","Choisissez un client à risque et planifiez la prochaine étape réaliste.",["Résumez les signaux de risque.","Identifiez les personnes à impliquer.","Proposez une action vérifiable."],[["Pourquoi le client est-il à risque ?","Signaux observés."],["Qui faut-il impliquer ?","Des deux côtés."],["Que proposez-vous ?","Action, objectif et date de suivi."]]],
    "tradeoff":["Expliquez une décision difficile","Traitez un cas où la demande du client, l’effort et l’usage responsable ne vont pas dans le même sens.",["Nommez les intérêts concernés.","Évaluez les conséquences.","Décidez et expliquez pourquoi."],[["Quels intérêts s’opposent ?","Client, utilisateurs et entreprise."],["Quelles conséquences sont possibles ?","À court et long terme."],["Quelle est votre décision ?","Décision et justification."]]],
    "success-story":["Documentez une réussite client","Décrivez ce qui s’est amélioré pour le client et votre contribution.",["Décrivez la situation de départ.","Montrez le principal changement.","Notez ce que vous referiez."],[["Quelle était la situation de départ ?","Problème ou objectif."],["Qu’est-ce qui a changé ?","Bénéfice concret."],["Qu’avez-vous appris ?","Un point pour la prochaine fois."]]],
    "explain":["Expliquez-le à une nouvelle personne","Expliquez à une personne récemment arrivée un sujet que vous maîtrisez maintenant.",["Choisissez un sujet précis.","Évitez les abréviations internes.","Demandez ce qui reste flou."],[["Quel sujet expliquez-vous ?","Un sujet bien défini."],["Qu’est-ce qui était difficile ?","Question ou hésitation."],["Que changeriez-vous ?","Une amélioration."]]],
    "fresh-eyes":["Faites le bilan des 100 jours","Revenez sur vos 100 premiers jours. Vous choisissez ce qui reste privé et ce que vous partagez.",["Relisez vos réponses.","Choisissez un point à conserver et un à améliorer.","Décidez ce que vous souhaitez partager."],[["Qu’est-ce qui a facilité votre arrivée ?","Ce qui devrait rester."],["Qu’est-ce qui a été inutilement difficile ?","Processus, information ou situation."],["Que faudrait-il changer ?","Une proposition réaliste."],["Que souhaitez-vous partager ?","Vous pouvez laisser ce champ vide.",false]]]
  }
};
